### ISSUE TITLE
Rotatie animation with multiple cars

### ISSUE THREAD

**Issue by TheReprator** [mohak1712/UberUX#8]
Thanks for the great explanation.

My app works great with single card movement even on turn but when it comes to animate or move multiple cars, it started flickering.

Can u please help me out? It would be great if you can provide some example.

**Comment by AJITMEENA777** [comment]
Ok

**Comment by TheReprator** [comment]
@AJITMEENA777 , I didn't get it, can u provide me with some some example

**Comment by AJITMEENA777** [comment]
Yes

**Comment by TheReprator** [comment]
@AJITMEENA777 please share the code, if you have

**Comment by TheReprator** [comment]
@AJITMEENA777 , actually it's a whole project and that's of company
